### ISSUE TITLE
Playlist null pointer exception for unix

### ISSUE THREAD

**Issue by Tyler-Hilbert** [Tyler-Hilbert/MusicManiac#1]
When selecting a playlist on unix systems:

Caused by: java.lang.NullPointerException
    at musicmaniac.PlaylistLoader.loadDirectory(PlaylistLoader.java:17)
    at musicmaniac.PlaylistLoader.<init>(PlaylistLoader.java:13)
    at musicmaniac.MusicManiac.start(MusicManiac.java:57)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
    ... 1 more
Exception running application musicmaniac.MusicManiac

**Comment by Tyler-Hilbert** [comment]
This is fixed by running: sudo apt-get install libavformat-dev
